# DataFrames
When you Combine Multiple Series

In [102]:
import numpy as np
import pandas as pd

# Creating a DataFrame

In [103]:
data = {
    'Name' : ['Elena', 'Mike', 'Bean', 'John'],
    'Age' : [22, 34, 43, 36],
    'City' : ['London', 'Paris', 'Berlin', 'New York'],
    'Salary' : [90000, 80000, 75000, 88000]
} # dictionary

In [104]:
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0  Elena   22    London   90000
1   Mike   34     Paris   80000
2   Bean   43    Berlin   75000
3   John   36  New York   88000

In [105]:
list1 = [
    ['Elena', 22, 'London', 90000],
    ['Mike', 34, 'Paris', 80000],
    ['Bean', 43, 'Berlin', 75000],
    ['John', 36, 'New York', 88000]
] # list
df2 = pd.DataFrame(list1)
df2

       0   1         2      3
0  Elena  22    London  90000
1   Mike  34     Paris  80000
2   Bean  43    Berlin  75000
3   John  36  New York  88000

In [106]:
columns = ['Name', 'Age', 'City', 'Salary']
df3 = pd.DataFrame(list1, columns = columns)
df3

    Name  Age      City  Salary
0  Elena   22    London   90000
1   Mike   34     Paris   80000
2   Bean   43    Berlin   75000
3   John   36  New York   88000

# Selection and Indexing of Columns

In [107]:
df3

    Name  Age      City  Salary
0  Elena   22    London   90000
1   Mike   34     Paris   80000
2   Bean   43    Berlin   75000
3   John   36  New York   88000

In [108]:
df3['Name']

0    Elena
1     Mike
2     Bean
3     John
Name: Name, dtype: object

In [109]:
df3['Salary']

0    90000
1    80000
2    75000
3    88000
Name: Salary, dtype: int64

In [110]:
df3[['Name', 'City']]

    Name      City
0  Elena    London
1   Mike     Paris
2   Bean    Berlin
3   John  New York

### Creating a New Column

In [111]:
df3

    Name  Age      City  Salary
0  Elena   22    London   90000
1   Mike   34     Paris   80000
2   Bean   43    Berlin   75000
3   John   36  New York   88000

In [112]:
df3["Designation"] = ['Doctor', 'Engineer', 'Pediatrician', 'Accountant']

In [113]:
df3

    Name  Age      City  Salary   Designation
0  Elena   22    London   90000        Doctor
1   Mike   34     Paris   80000      Engineer
2   Bean   43    Berlin   75000  Pediatrician
3   John   36  New York   88000    Accountant

### Removing Columns

In [114]:
df3.drop('Designation', axis = 1, inplace = True) 
# by default axis = 0 (Horizontal)
# inplace = True means Removes the content from the main data

In [115]:
df3

    Name  Age      City  Salary
0  Elena   22    London   90000
1   Mike   34     Paris   80000
2   Bean   43    Berlin   75000
3   John   36  New York   88000

In [116]:
df3.drop(['City', 'Salary'], axis = 1) # Deletes  Vertical Columns

    Name  Age
0  Elena   22
1   Mike   34
2   Bean   43
3   John   36

In [117]:
df3.drop(0, axis = 0) # Horizontal rows

   Name  Age      City  Salary
1  Mike   34     Paris   80000
2  Bean   43    Berlin   75000
3  John   36  New York   88000

### Selecting Rows

In [118]:
df3

    Name  Age      City  Salary
0  Elena   22    London   90000
1   Mike   34     Paris   80000
2   Bean   43    Berlin   75000
3   John   36  New York   88000

In [119]:
df3.loc[0]

Name       Elena
Age           22
City      London
Salary     90000
Name: 0, dtype: object

In [120]:
df3.loc[[0,1,2]]

    Name  Age    City  Salary
0  Elena   22  London   90000
1   Mike   34   Paris   80000
2   Bean   43  Berlin   75000

In [121]:
df3.iloc[[0,1,2]] # Index Location

    Name  Age    City  Salary
0  Elena   22  London   90000
1   Mike   34   Paris   80000
2   Bean   43  Berlin   75000

### Selecting Subsets of Rows and Columns

In [122]:
df3

    Name  Age      City  Salary
0  Elena   22    London   90000
1   Mike   34     Paris   80000
2   Bean   43    Berlin   75000
3   John   36  New York   88000

In [123]:
df3.loc[[0,1],['City', 'Salary']]

     City  Salary
0  London   90000
1   Paris   80000

In [124]:
df3.loc[[2,3],['Name', 'Age']]

   Name  Age
2  Bean   43
3  John   36

### Conditional Selection

In [125]:
df3

    Name  Age      City  Salary
0  Elena   22    London   90000
1   Mike   34     Paris   80000
2   Bean   43    Berlin   75000
3   John   36  New York   88000

In [126]:
df3[df3['Age'] > 30]

   Name  Age      City  Salary
1  Mike   34     Paris   80000
2  Bean   43    Berlin   75000
3  John   36  New York   88000

In [127]:
df3[(df3['Age'] > 30) & (df3['City'] == 'Paris')]

   Name  Age   City  Salary
1  Mike   34  Paris   80000